### ISSUE TITLE
Update for latest versions of Rive and ThorVG

### ISSUE THREAD

**Issue by projectitis** [rive-app/rive-tizen#68]
I would love to see this updated for the latest versions of Rive and ThorVG :)

**Comment by hermet** [comment]
@projectitis Hi, rive_tizen hasn't been updated for a while though you can use it since it's working. I will try to rebase the rive-tizen with the latest rive and let you know the result. (I might take some days.)

**Comment by projectitis** [comment]
It looks like the rive renderer has changed quite a lot. Rive have added a new gradient type (`SweepGradient`) and also a `RenderImage` class (previously only `RenderPath` and `RenderPaint`).

**Comment by projectitis** [comment]
@hermet [I have started work on this](https://github.com/DeriveSDK/rive-tizen/tree/feature/update-to-latest-rive). I may not be able to complete all of it, but I can make a start.

**Comment by hermet** [comment]
@projectitis cool, thanks for your effort!

**Comment by luigi-rosso** [comment]
We're not actually using the sweep gradient, it's mostly there as an example of the kind of abstraction the renderer would support. We should probably remove it for now from the renderer definition. @mikerreed

**Comment by projectitis** [comment]
Ok, thank you @luigi-rosso! Please let me know if there are other methods that are similar and also don't need to be implemented :)

**Comment by projectitis** [comment]
Update: I've been working on this on and off for the past week or so. Rendering curves and fills is working, but gradients (using the new 'shader' approach) are causing exceptions. I haven't started implementing the image methods/shaders yet.

I'll keep working on it when I can, but feel free to look at and/or contribute to my fork if anyone is keen: https://github.com/DeriveSDK/rive-tizen/tree/feature/update-to-latest-rive

There are also some areas where I think the ThorVG renderer can be optimized, which I'll look at later. For example I see a lot of calls to `paint->duplicate()` for Rive to work on copies of the ThorVG paints instead of directly on them, and I'm not entirely sure if that is required or just adding overhead?

**Comment by projectitis** [comment]
Gradients working now. It was a pointer ownership issue.
Now only images to go (plus testing).

**Comment by projectitis** [comment]
I now have a buggy drawImage implementation, but it's a start!

This is what it is supposed to look like:
![image](https://user-images.githubusercontent.com/32183808/165446528-274618e8-4a53-4ea7-bff5-477146c80847.png)

This is what it renders as:
![image](https://user-images.githubusercontent.com/32183808/165446729-fe18624e-03f1-42e7-8e72-e4a5d2aaf78c.png)

I have some theories for what is going wrong:

- Color channels are different between tvg and rive
- Images are referenced by center maybe?
- Maybe translation is also happening after rotation. Not sure.

@hermet I think I have almost reached as far as I can with my current knowledge of ThorVG.
Could you create a branch on the rive-tizen repo for this? - for example `update-to-v7-runtime` - then I can submit a PR to that branch.

There is still the following work to be done:

- Fix drawImage
- Implement drawImageMesh
- Implement fill using image

I have attached some files I was using for testing.
[test-riv-files.zip](https://github.com/rive-app/rive-tizen/files/8569118/test-riv-files.zip)

**Comment by projectitis** [comment]
@luigi-rosso image fills are supported by the renderer (i.e. image shader) but I can't see how to create these in Rive. Is this also a currently unsupported feature?

**Comment by hermet** [comment]
@projectitis great work, 

ok, so my opinion. 

1. about duplicate(), 
I believe it won't affect performance a lot, but yes we can optimize it by avoiding it in rive-tizen side?. need to check it's really neceesary behavior... 

2. about color channel
Do you use static png loader in thorvg? it has a known channel issue, if those images are png type. If the condition is correct, you can test with this temporary patch,  https://github.com/Samsung/thorvg/pull/1112. 

3. about Rotation
Currently the pivot is fixed at the top-left corner of the tvg::paint geomtery. Though it's a bit annoying, I think you can make it properly working. For that, you can try to understand with https://github.com/Samsung/thorvg/blob/master/src/examples/SceneTransform.cpp,
Obivously, tvg need a function to set the pivot of the nodes...

4. about meshed Images
The texture mapping logic is prepared in thorvg (for transformed images) but it's just fixed at 2 triangle meshes, 
https://github.com/Samsung/thorvg/blob/master/src/lib/sw_engine/tvgSwRasterTexmap.h
For meshed images for rive, It needs improvement, guess it may require a bunch of code to fill up to tvg apis...

5. about contribution.
I will prepare the branch later today.
But I think @luigi-rosso could help you the access to this repo. @luigi-rosso could you please help him?


* Thesedays I'm totally into a writing a book, it's my personal task, so I'm fully working at my free time for it (due to deadline). So frankly, lack of time to code thesedays, Just hope it's finished soon then come back to opensource work, sorry for that @projectitis

**Comment by projectitis** [comment]
Wow @hermet - that is great news about your book! I wish you good luck, and I totally understand. Please share it once you have published it! Thank you for the information :)

**Comment by projectitis** [comment]
Good progress in some spare time after work this evening!

- Color channel was fixed by the patch - at least in the case of this particular PNG. But I will need to check with all sorts of PNG images to check that the patch is ok in all cases (you are also dubious, @hermet, judging by your comments on the PR).

- The image transforms were fixed by nesting the picture in a scene and offsetting it by half the width and height to move the registration point to the center.

- I also fixed another potential issue with save/restore. It is now saving and restoring the transform AND the clip path (previously only the transform). This was discovered by reading the Skia docs on save/restore, but I haven't seen an error due to this yet in any rive files I have tested.

Outstanding questions for @luigi-rosso when you are able :) 

- Could you please create a branch for `update-to-v7-runtime` that I can contribute to?

- Does Rive currently support image meshes or can this be ignored for now?

- Any ideas on this? : The current ThorVG implementation has a strange design where the very first clipPath that is ever provided is saved as the "BG clip path" (i.e. the clip path of the art board) and every single draw call is subsequently clipped to that path, as well as any other clip path that is set. However:

  1. The Skia implementation does not do this, but still clips correctly to the artboard
  2. If this code is removed, the objects outside the artboard are visible, even with the save/restore fix as above
  3. I thought I read that Rive will soon (or mavbe already does) have the option not to draw a background. If such a rive file is rendered, will the first clipPath provided still be the background/artboard clip path?

**Comment by projectitis** [comment]
@hermet I fixed the clipping - no longer need to store the first clipping path as the "BG" clipping path!
There were a few things that needed to be done:

* Do not delete clipping path after every draw (keep it)
* New clipping path should intersect with existing one, not replace it
* And finally, save/restore should save a duplicate of the clipping path. It was saving a pointer only, so of course the saved clipping path continued to be modified

**Comment by hermet** [comment]
@projectitis good job. thanks. we can incrementally improve the feature, do you think your patch is ready to go in?

**Comment by projectitis** [comment]
@hermet The new branch is stable and works with all `.riv` files I have tested so far.
The only problem is that I have not updated the examples yet. I am trying to get Elementary/EFL working on Windows :( 

If you prefer, the examples can be fixed later.

**Comment by luigi-rosso** [comment]
> Ok, thank you @luigi-rosso! Please let me know if there are other methods that are similar and also don't need to be implemented :)
> 
> I see Rive has a "quad" (quadTo) verb/command. Is this used? ThorVG currently only has cubic.

No, not yet although we may use it when we add text!

**Comment by luigi-rosso** [comment]
Sorry for my delay! I've been on paternity leave getting screamed at by both my new baby and the toddler and I've been letting a lot of these notifications accumulate. It really is the best of times, nonetheless :) 👶🏼 🍼 

> * Could you please create a branch for `update-to-v7-runtime` that I can contribute to?

I made you a ```write``` contributor, I think you can do this yourself now. Let me know if not! 

> * Does Rive currently support image meshes or can this be ignored for now?

It doesn't in production, but a lot of our example files are already using it. The feature is slotted for launch very very soon.

> * Any ideas on this? : The current ThorVG implementation has a strange design where the very first clipPath that is ever provided is saved as the "BG clip path" (i.e. the clip path of the art board) and every single draw call is subsequently clipped to that path, as well as any other clip path that is set. However:
>   
>   1. The Skia implementation does not do this, but still clips correctly to the artboard
>   2. If this code is removed, the objects outside the artboard are visible, even with the save/restore fix as above
>   3. I thought I read that Rive will soon (or mavbe already does) have the option not to draw a background. If such a rive file is rendered, will the first clipPath provided still be the background/artboard clip path?

We have the option (in the editor) to disable clipping of the artboard (so no first rect clip). Transparency is also supported (no background) but it's separate from clipping. Rive will call something like ```if(clip) renderer->clip(artboardPath);``` before calling ```if(background) renderer->drawPath(artboardPath);```. It's a little more nuanced than that as there can be multiple backgrounds, but general idea is the same. Our [Skia based viewer](https://github.com/rive-app/rive-cpp/tree/master/skia/viewer) is a good test/known-good environment to run files in.

**Comment by luigi-rosso** [comment]
> @luigi-rosso image fills are supported by the renderer (i.e. image shader) but I can't see how to create these in Rive. Is this also a currently unsupported feature?

Image fills are currently only supported on image draw operations. Not on vector geometry, and there's no current plan to enable that soon. I think some "design ideas" are leaking into the runtime. @mikerreed we may want to put some comments in about that or save them in a branch

**Comment by projectitis** [comment]
Wow @luigi-rosso - huge congratulations! That is awesome news 😄 🎉 

Thanks for all the info. As in the thread above, I believe the latest version of the renderer is ready to be merged - except for the examples, which I haven't updated. I don't run linux, so I'm currently trying to get EFL working on windows in order to tackle those!

**Comment by hermet** [comment]
@luigi-rosso congratulations :)

@projectitis I think launching the examples with EFL on windows would be a bit annoying by you. I fixed the example build breaks.

**Comment by projectitis** [comment]
Thanks @hermet, very much appreciated, especially since you are so busy with your book :)

I have not been able to get Elementary working on windows because of some unsupported dependencies it has. But I am recreating the examples using GLFW3 and will add them to the repo later in a 'win' folder.

I am happy to close this issue.
